# Generated by Django 5.1.5 on 2025-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Выполнена'), ('archived', 'Архивирована')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('specific', models.TextField(verbose_name='Конкретность')),
                ('measurable', models.TextField(verbose_name='Измеримость')),
                ('achievable', models.TextField(verbose_name='Достижимость')),
                ('relevant', models.TextField(verbose_name='Актуальность')),
                ('time_bound', models.TextField(verbose_name='Сроки')),
            ],
        ),
        migrations.CreateModel(
            name='UserValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
    ]
