# Generated by Django 5.1.5 on 2025-02-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.value'),
        ),
        migrations.AddField(
            model_name='goal',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.value'),
        ),
        migrations.AlterUniqueTogether(
            name='uservalue',
            unique_together={('user', 'value')},
        ),
    ]
